src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: 'app_users')]
#[UniqueEntity(fields: ['username'], message: 'There is already an account with this username')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    #[Assert\NotBlank]
    #[Assert\Email]
    private $username;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function getEmail() : string
    {
        return $this->username;
    }

    public function getName(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function addRole(string $role)
    {
        if(!in_array($role, $this->roles)) {
            $this->roles[] = $role;
        }
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified ?? false;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Button\LinkToRoute;
use App\Form\FastRequestType;
use App\Model\FastRequest;
use App\Repository\PageRepository;
use App\Repository\ProductRepository;
use App\Service\OrderService;
use Doctrine\DBAL\Exception\DriverException;
use Doctrine\DBAL\Exception\TableNotFoundException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends AbstractController
{
    public function __construct(
        private readonly ProductRepository $productRepository,
        private readonly PageRepository $pageRepository,
        private readonly OrderService $orderService)
    {
    }

    public function default(): Response
    {
        $user = $this->getUser();

        //TODO: check routes exists
        if(!$user) {
            //$buttons[] = new LinkToRoute('app_register', 'button.register', 'primary', 'bi bi-1-circle');
            $buttons[] = new LinkToRoute('app_index', 'action.home', 'outline-primary', 'bi bi-1-circle');
            //$buttons[] = new LinkToRoute('app_login', 'button.login', 'outline-primary', 'bi bi-2-square');
        } else {
            $buttons[] = new LinkToRoute('app_index', 'action.home', 'outline-primary', 'bi bi-1-circle');
        }

        return$this->render('default/default.html.twig', [
            'buttons' => $buttons,
        ]);
    }

    public function index(): Response
    {
        try {
            $products = $this->productRepository->findMain();
        } catch (TableNotFoundException $e) {
            $this->addFlash('error', sprintf('error.table_not_found_for %s', 'products'));
            $products = [];
        } catch (DriverException $e) {
            $this->addFlash('danger', $e->getMessage());
            $products = [];
        } catch (\Exception $e) {
            // TODO: this code never reaches. You may add custom exception to catch
            throw $e;
        }

        $buttons = [];

        if(count($products) === 0) {
            $this->addFlash('warning', 'No products found');
            $buttons[] = new LinkToRoute('admin', 'button.admin', 'primary');
        }

        $form = $this->createForm(FastRequestType::class, new FastRequest(), [
            'action' => $this->generateUrl('app_fast_request'),
            'method' => 'POST',
        ]);

        //TODO: check routes exists
//        $buttons[] = new LinkToRoute('default', 'button.more', 'primary', 'bi bi-1-circle');
//        $buttons[] = new LinkToRoute('default_index', 'button.subscribe', 'outline-primary', 'bi bi-2-square');

        return$this->render('default/index.html.twig', [
            'buttons' => $buttons,
            'products' => $products,
            'fast_form' => $form
        ]);
    }

    #[Route('/contact', name: 'app_contact', methods: ['GET'])]
    public function contact(string $page = 'contact'): Response
    {
        $page = $this->pageRepository->findOneBy(['slug' => $page]);

        if(!$page) {
            throw new NotFoundHttpException('Page not found');
        }

        return $this->render('page/show.html.twig', [
            'page' => $page,
        ]);
    }

    #[Route('/request', name: 'app_fast_request', methods: ['GET', 'POST'])]
    public function fastRequest(Request $request): Response
    {
        $form = $this->createForm(FastRequestType::class, new FastRequest(), [
            'action' => $this->generateUrl('app_fast_request'),
            'method' => 'POST',
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $order = $this->orderService->fastRequest($form->getData());

            $this->addFlash('success', sprintf('%s flash.success.created', $order->getUuid()));

            return $this->redirectToRoute('app_order_success', ['uuid' => $order->getUuid()]);
        }

        return $this->render('order/new.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

templates/default/contact.html.twig
{% extends 'layout.html.twig' %}

{% block main %}
    <h1 class="mb-4">{{ page.title }}</h1>

    <div class="row">

        <div class="col-md-6">
            <p>{{ page.description }}</p>
            <div>{{ page.text|raw }}</div>
        </div>
    </div>
{% endblock %}

templates/default/default.html.twig
{% extends "default.html.twig" %}

templates/default/features.html.twig
{% extends 'layout.html.twig' %}

{% block breadcrumbs %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('app_index') }}">{{ 'brcmbs.home'|trans }}</a></li>
            <li class="breadcrumb-item" aria-current="page">{{ 'title.features'|trans }}</li>
        </ol>
    </nav>
{% endblock %}

{% block main %}
    <h1 class="mb-4">{{ 'title.features'|trans }}</h1>

    <div class="row">
        <div class="col-md-9">
            {% if topics is not defined %}
                <h4>No topics defined</h4>
            {% elseif topics|length == 0 %}
                <p><b>Topics list is empty</b></p>
            {% else %}
            <ol class="list-group list-group-numbered">
                {% for item in topics %}
                <li class="list-group-item d-flex justify-content-between align-items-start">
                    <div class="ms-2 me-auto">
                        <div class="fw-bold">{{ item.title }}</div>
                        {{ item.description }}
                    </div>
{#                    <span class="badge bg-primary rounded-pill">{{ item.answers|length }}</span>#}
                </li>
                {% endfor %}
            </ol>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/default/inbox.html.twig
{% extends 'default/index.html.twig' %}

{%block hero %}

{% endblock hero %}

{% block main %}
    <h1>Inbox</h1>
    {% if inbox is not defined %}
        <H3>No inbox items</H3>
        <!-- TODO: no inbox variable -->
    {% elseif inbox|length == 0 %}
        <H4>Empty inbox</H4>
        <!-- TODO: inbox is empty. Would you to add a new one? -->
    {% else %}
        <ul class="list-group">
        {% for i, item in inbox %}
            <li class="list-group-item">
                <input class="form-check-input me-2" type="checkbox" value="" id="firstCheckbox">
                <label class="form-check-label" for="firstCheckbox">{{ item.time }} {{ item.recipient }} {{ item.subject }} {{ item.text }}</label>
            </li>
        {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

templates/default/index.html.twig
{#{% extends 'layout.html.twig' %} #}{# TODO: inherits from the controller #}
{% extends 'default_layout.html.twig' %}

{% block title %}{{ app_name }} / Проектування та виробництво ліфтового обладнання {% endblock %}
{% block hero %}
    <div class="container col-xxl-8 px-4 py-1">
        <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
            <div class="col-10 col-sm-8 col-lg-6">
                <img src="{{ asset('build/images/logo0.png') }}" class="d-block mx-lg-auto img-fluid" alt="{{ app_domain }} {{ app_name }}" width="250" loading="lazy">
            </div>
            <div class="col-lg-6">
                <h1 class="mb-4">Наша компанія</h1>
                <p >
                    Є автором та виробником універсального гідравлічного обладнання. Гідравлічне підйомне обладнання пройшло всі технічні випробування та відповідає міжнародним вимогам та технічним умовам експлуатації.</p>
                <div class="position-relative">
                    <a href="{{ path('app_contact') }}" type="button" class="btn btn-outline-main px-4 position-absolute end-0">{{ 'action.details'|trans }}</a>
                </div>
            </div>
        </div>
        <hr class="hr">
    </div>
{% endblock %}

{% block main %}{% endblock %}

templates/default/info.html.twig
{% extends 'layout.html.twig' %}

{% block breadcrumbs %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ path('app_index') }}">{{ 'brcmbs.home'|trans }}</a></li>
            <li class="breadcrumb-item" aria-current="page">{{ 'title.info'|trans }}</li>
        </ol>
    </nav>
{% endblock %}

{% block main %}
    <h1 class="mb-4">{{ 'title.info'|trans }}</h1>

    <div class="row">
        <div class="col-md-6">
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><b>Name:</b> {{ app_name }}</li>
                <li class="list-group-item"><b>Version:</b> {{ app_version }}</li>
                <li class="list-group-item"><b>Environment:</b> {{ app.environment|upper }}</li>
                <li class="list-group-item"><b>Debug:</b> {{ app.debug ? 'Yes' : 'No' }}</li>
            </ul>
        </div>
    </div>
{% endblock %}

templates/default/login.html.twig
{% extends 'default.html.twig' %} {# TODO: template is deprecated #}

{% block main %}
    <main class="form-signin w-100 m-auto">
        <div class="container">
            <div class="row">

                <div class="text-center d-flex justify-content-center mb-4">
                    <div class="icon"></div>
                </div>

                <div class="text-center">
                    <h1 class="h3 mb-5 fw-normal"><i class="bi bi-people-fill"></i> Member's area</h1>
                </div>
                {% if error %}
                    <div class="alert alert-danger" role="alert">
                        {{ error.messageKey|trans(error.messageData, 'security') }}
                    </div>
                {% endif %}
                <div class="card">
                    <div class="card-body text-dark ">

                        {% if app.user %}
                            {# TODO: set default module for the user #}
                            <a class="w-100 btn btn-lg btn-outline-primary btn-common" href="{{ path(app_default_module) }}">{{ app.user.userIdentifier }}</a>
                            <p class="mb-3 mt-3 text-center">or</p>
                            <a class="w-100 btn btn-lg btn-outline-primary" href="{{ path('app_logout') }}">{{ 'logout'|trans }}</a>

                        {% else %}

                            <form method="post" action="{{ path('login') }}">
                                <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
                                <div class="mb-3">
                                    <label for="username" class="form-label">{{ 'form.label.email'|trans }}</label>
                                    <input type="email" class="form-control" id="username" name="_username" value="{% if last_username is defined %}{{ last_username }}{% endif %}" aria-describedby="emailHelp">
                                </div>
                                <div class="mb-3">
                                    <label for="password" class="form-label">{{ 'form.label.password'|trans }}</label>
                                    <input type="password" id="password" name="_password" class="form-control">
                                </div>
                                <div class="mb-3 form-check">
                                    <input type="checkbox" class="form-check-input" id="remember" name="_remember_me">
                                    <label class="form-check-label" for="remember">{{ 'form.label.remember_me'|trans }}</label>
                                </div>
                                <button class="w-100 btn btn-lg btn-outline-primary btn-common" type="submit">{{ 'button.login'|trans }}</button>

                                {#                        <div class="col-md-6 mt-5">#}
                                {#                            <p>Or you can login with social network:</p>#}
                                {#                            <a href="{{ path('hwi_oauth_service_redirect', {'service': 'google' }) }}"  class="btn-outline-secondary btn">#}
                                {#                                <span>Login with Google</span>#}
                                {#                            </a>#}
                                {#                        </div>#}
                            </form>

                        {% endif %}

                    </div>
                </div>

{#                <p class="mt-5 mb-3 text-muted text-center">&copy; 2022-2023 {{ app_name|capitalize }}</p>#}

            </div>
        </div>
    </main>
{% endblock main %}